/** 자주 쓰는 품목 프리셋 — 이름 직접 입력의 보조. category는 공통 분류 시드(V2) 이름과 일치해야 자동 매칭됨. */
export interface ItemPreset {
  name: string
  emoji: string
  /** 공통 분류 이름 (없거나 미일치면 분류 자동 선택 생략) */
  category: string
  /** 기본 단위 — 단위 칸이 비어 있을 때만 채움 */
  unit?: string
}

export const ITEM_PRESETS: ItemPreset[] = [
  // 유제품
  { name: '우유', emoji: '🥛', category: '유제품', unit: '팩' },
  { name: '치즈', emoji: '🧀', category: '유제품', unit: '장' },
  { name: '모짜렐라치즈', emoji: '🧀', category: '유제품', unit: '봉지' },
  { name: '요거트', emoji: '🥛', category: '유제품', unit: '개' },
  { name: '버터', emoji: '🧈', category: '유제품', unit: '개' },
  { name: '생크림', emoji: '🥛', category: '유제품', unit: '팩' },
  { name: '연유', emoji: '🥛', category: '유제품', unit: '통' },
  // 신선식품 (수산물·건어물 포함)
  { name: '계란', emoji: '🥚', category: '신선식품', unit: '알' },
  { name: '두부', emoji: '🍲', category: '신선식품', unit: '모' },
  { name: '순두부', emoji: '🍲', category: '신선식품', unit: '팩' },
  { name: '김치', emoji: '🥬', category: '신선식품', unit: '통' },
  { name: '콩나물', emoji: '🌱', category: '신선식품', unit: '봉지' },
  { name: '어묵', emoji: '🍢', category: '신선식품', unit: '봉지' },
  { name: '게맛살', emoji: '🦀', category: '신선식품', unit: '팩' },
  { name: '고등어', emoji: '🐟', category: '신선식품', unit: '마리' },
  { name: '갈치', emoji: '🐟', category: '신선식품', unit: '마리' },
  { name: '오징어', emoji: '🦑', category: '신선식품', unit: '마리' },
  { name: '새우', emoji: '🦐', category: '신선식품', unit: '팩' },
  { name: '조개', emoji: '🦪', category: '신선식품', unit: '봉지' },
  { name: '김', emoji: '🍙', category: '신선식품', unit: '봉' },
  { name: '멸치', emoji: '🐟', category: '신선식품', unit: '봉지' },
  { name: '미역', emoji: '🌿', category: '신선식품', unit: '봉지' },
  { name: '다시마', emoji: '🌿', category: '신선식품', unit: '봉지' },
  // 채소
  { name: '양파', emoji: '🧅', category: '채소', unit: '개' },
  { name: '마늘', emoji: '🧄', category: '채소', unit: '통' },
  { name: '대파', emoji: '🥬', category: '채소', unit: '단' },
  { name: '감자', emoji: '🥔', category: '채소', unit: '개' },
  { name: '고구마', emoji: '🍠', category: '채소', unit: '개' },
  { name: '당근', emoji: '🥕', category: '채소', unit: '개' },
  { name: '오이', emoji: '🥒', category: '채소', unit: '개' },
  { name: '애호박', emoji: '🥒', category: '채소', unit: '개' },
  { name: '가지', emoji: '🍆', category: '채소', unit: '개' },
  { name: '무', emoji: '⚪', category: '채소', unit: '개' },
  { name: '배추', emoji: '🥬', category: '채소', unit: '포기' },
  { name: '양배추', emoji: '🥬', category: '채소', unit: '통' },
  { name: '상추', emoji: '🥬', category: '채소', unit: '봉지' },
  { name: '깻잎', emoji: '🍃', category: '채소', unit: '봉지' },
  { name: '시금치', emoji: '🌿', category: '채소', unit: '단' },
  { name: '브로콜리', emoji: '🥦', category: '채소', unit: '개' },
  { name: '파프리카', emoji: '🫑', category: '채소', unit: '개' },
  { name: '청양고추', emoji: '🌶️', category: '채소', unit: '봉지' },
  { name: '버섯', emoji: '🍄', category: '채소', unit: '팩' },
  // 과일
  { name: '사과', emoji: '🍎', category: '과일', unit: '개' },
  { name: '배', emoji: '🍐', category: '과일', unit: '개' },
  { name: '바나나', emoji: '🍌', category: '과일', unit: '송이' },
  { name: '귤', emoji: '🍊', category: '과일', unit: '개' },
  { name: '토마토', emoji: '🍅', category: '과일', unit: '개' },
  { name: '방울토마토', emoji: '🍅', category: '과일', unit: '팩' },
  { name: '딸기', emoji: '🍓', category: '과일', unit: '팩' },
  { name: '포도', emoji: '🍇', category: '과일', unit: '송이' },
  { name: '수박', emoji: '🍉', category: '과일', unit: '통' },
  { name: '참외', emoji: '🍈', category: '과일', unit: '개' },
  { name: '복숭아', emoji: '🍑', category: '과일', unit: '개' },
  { name: '키위', emoji: '🥝', category: '과일', unit: '개' },
  { name: '블루베리', emoji: '🫐', category: '과일', unit: '팩' },
  { name: '레몬', emoji: '🍋', category: '과일', unit: '개' },
  { name: '아보카도', emoji: '🥑', category: '과일', unit: '개' },
  // 육류
  { name: '삼겹살', emoji: '🥓', category: '육류', unit: 'g' },
  { name: '목살', emoji: '🥩', category: '육류', unit: 'g' },
  { name: '돼지고기', emoji: '🥩', category: '육류', unit: 'g' },
  { name: '소고기', emoji: '🥩', category: '육류', unit: 'g' },
  { name: '다짐육', emoji: '🥩', category: '육류', unit: 'g' },
  { name: '닭고기', emoji: '🍗', category: '육류', unit: '팩' },
  { name: '닭가슴살', emoji: '🍗', category: '육류', unit: '팩' },
  { name: '베이컨', emoji: '🥓', category: '육류', unit: '팩' },
  { name: '햄', emoji: '🍖', category: '육류', unit: '개' },
  { name: '스팸', emoji: '🥫', category: '육류', unit: '캔' },
  { name: '소시지', emoji: '🌭', category: '육류', unit: '봉지' },
  // 냉동식품
  { name: '만두', emoji: '🥟', category: '냉동식품', unit: '봉지' },
  { name: '돈까스', emoji: '🍖', category: '냉동식품', unit: '팩' },
  { name: '치킨너겟', emoji: '🍗', category: '냉동식품', unit: '봉지' },
  { name: '핫도그', emoji: '🌭', category: '냉동식품', unit: '개' },
  { name: '떡갈비', emoji: '🍖', category: '냉동식품', unit: '팩' },
  { name: '냉동볶음밥', emoji: '🍚', category: '냉동식품', unit: '봉지' },
  { name: '냉동피자', emoji: '🍕', category: '냉동식품', unit: '개' },
  { name: '냉동과일', emoji: '🍓', category: '냉동식품', unit: '봉지' },
  { name: '아이스크림', emoji: '🍦', category: '냉동식품', unit: '개' },
  { name: '얼음', emoji: '🧊', category: '냉동식품', unit: '봉지' },
  // 음료 (주류 포함)
  { name: '생수', emoji: '💧', category: '음료', unit: '병' },
  { name: '탄산수', emoji: '🫧', category: '음료', unit: '병' },
  { name: '콜라', emoji: '🥤', category: '음료', unit: '캔' },
  { name: '제로콜라', emoji: '🥤', category: '음료', unit: '캔' },
  { name: '사이다', emoji: '🥤', category: '음료', unit: '캔' },
  { name: '주스', emoji: '🧃', category: '음료', unit: '병' },
  { name: '이온음료', emoji: '🥤', category: '음료', unit: '병' },
  { name: '두유', emoji: '🥛', category: '음료', unit: '팩' },
  { name: '보리차', emoji: '🍵', category: '음료', unit: '병' },
  { name: '커피', emoji: '☕', category: '음료', unit: '개' },
  { name: '커피믹스', emoji: '☕', category: '음료', unit: '통' },
  { name: '맥주', emoji: '🍺', category: '음료', unit: '캔' },
  { name: '소주', emoji: '🍶', category: '음료', unit: '병' },
  { name: '와인', emoji: '🍷', category: '음료', unit: '병' },
  { name: '막걸리', emoji: '🍶', category: '음료', unit: '병' },
  // 간식
  { name: '라면', emoji: '🍜', category: '간식', unit: '봉지' },
  { name: '과자', emoji: '🍪', category: '간식', unit: '봉지' },
  { name: '빵', emoji: '🍞', category: '간식', unit: '개' },
  { name: '초콜릿', emoji: '🍫', category: '간식', unit: '개' },
  { name: '젤리', emoji: '🍬', category: '간식', unit: '봉지' },
  { name: '사탕', emoji: '🍭', category: '간식', unit: '봉지' },
  { name: '떡', emoji: '🍡', category: '간식', unit: '팩' },
  { name: '팝콘', emoji: '🍿', category: '간식', unit: '봉지' },
  { name: '시리얼', emoji: '🥣', category: '간식', unit: '통' },
  { name: '견과류', emoji: '🥜', category: '간식', unit: '봉지' },
  // 양념
  { name: '소금', emoji: '🧂', category: '양념', unit: '통' },
  { name: '설탕', emoji: '🍬', category: '양념', unit: '봉지' },
  { name: '고춧가루', emoji: '🌶️', category: '양념', unit: '봉지' },
  { name: '후추', emoji: '🧂', category: '양념', unit: '통' },
  { name: '식초', emoji: '🫗', category: '양념', unit: '병' },
  { name: '간장', emoji: '🍶', category: '양념', unit: '병' },
  { name: '고추장', emoji: '🌶️', category: '양념', unit: '통' },
  { name: '된장', emoji: '🫘', category: '양념', unit: '통' },
  { name: '쌈장', emoji: '🫘', category: '양념', unit: '통' },
  { name: '굴소스', emoji: '🦪', category: '양념', unit: '병' },
  { name: '액젓', emoji: '🐟', category: '양념', unit: '병' },
  { name: '맛술', emoji: '🍶', category: '양념', unit: '병' },
  { name: '올리고당', emoji: '🍯', category: '양념', unit: '병' },
  { name: '꿀', emoji: '🍯', category: '양념', unit: '병' },
  { name: '식용유', emoji: '🫗', category: '양념', unit: '병' },
  { name: '올리브유', emoji: '🫒', category: '양념', unit: '병' },
  { name: '참기름', emoji: '🫗', category: '양념', unit: '병' },
  { name: '들기름', emoji: '🫗', category: '양념', unit: '병' },
  { name: '케첩', emoji: '🍅', category: '양념', unit: '통' },
  { name: '마요네즈', emoji: '🥚', category: '양념', unit: '통' },
  { name: '카레가루', emoji: '🍛', category: '양념', unit: '봉지' },
  { name: '밀가루', emoji: '🌾', category: '양념', unit: '봉지' },
  { name: '부침가루', emoji: '🌾', category: '양념', unit: '봉지' },
  // 곡물·면 (V5에서 추가된 분류)
  { name: '쌀', emoji: '🍚', category: '곡물·면', unit: 'kg' },
  { name: '잡곡', emoji: '🌾', category: '곡물·면', unit: '봉지' },
  { name: '파스타면', emoji: '🍝', category: '곡물·면', unit: '봉지' },
  { name: '소면', emoji: '🍜', category: '곡물·면', unit: '봉지' },
  { name: '당면', emoji: '🍜', category: '곡물·면', unit: '봉지' },
  { name: '떡국떡', emoji: '🍡', category: '곡물·면', unit: '봉지' },
  // 생필품
  { name: '휴지', emoji: '🧻', category: '생필품', unit: '롤' },
  { name: '각티슈', emoji: '🧻', category: '생필품', unit: '곽' },
  { name: '물티슈', emoji: '💦', category: '생필품', unit: '팩' },
  { name: '키친타월', emoji: '🧻', category: '생필품', unit: '롤' },
  { name: '종량제봉투', emoji: '🗑️', category: '생필품', unit: '장' },
  { name: '음식물쓰레기봉투', emoji: '🗑️', category: '생필품', unit: '장' },
  { name: '지퍼백', emoji: '👝', category: '생필품', unit: '장' },
  { name: '건전지', emoji: '🔋', category: '생필품', unit: '개' },
  { name: '수세미', emoji: '🧽', category: '생필품', unit: '개' },
  { name: '고무장갑', emoji: '🧤', category: '생필품', unit: '켤레' },
  { name: '행주', emoji: '🧺', category: '생필품', unit: '장' },
  { name: '면봉', emoji: '⚪', category: '생필품', unit: '통' },
  // 위생용품 (여성/영유아 포함)
  { name: '샴푸', emoji: '🧴', category: '위생용품', unit: '통' },
  { name: '린스', emoji: '🧴', category: '위생용품', unit: '통' },
  { name: '바디워시', emoji: '🛁', category: '위생용품', unit: '통' },
  { name: '비누', emoji: '🧼', category: '위생용품', unit: '개' },
  { name: '손세정제', emoji: '🧴', category: '위생용품', unit: '개' },
  { name: '치약', emoji: '🪥', category: '위생용품', unit: '개' },
  { name: '칫솔', emoji: '🪥', category: '위생용품', unit: '개' },
  { name: '가글', emoji: '🦷', category: '위생용품', unit: '병' },
  { name: '치실', emoji: '🦷', category: '위생용품', unit: '개' },
  { name: '면도기', emoji: '🪒', category: '위생용품', unit: '개' },
  { name: '마스크', emoji: '😷', category: '위생용품', unit: '장' },
  { name: '생리대', emoji: '🩸', category: '위생용품', unit: '팩' },
  { name: '기저귀', emoji: '👶', category: '위생용품', unit: '팩' },
  { name: '세탁세제', emoji: '🧺', category: '위생용품', unit: '통' },
  { name: '섬유유연제', emoji: '🧺', category: '위생용품', unit: '통' },
  { name: '주방세제', emoji: '🧽', category: '위생용품', unit: '통' },
  { name: '욕실세정제', emoji: '🛁', category: '위생용품', unit: '통' },
  { name: '변기세정제', emoji: '🚽', category: '위생용품', unit: '통' },
  { name: '곰팡이제거제', emoji: '🦠', category: '위생용품', unit: '통' },
  { name: '탈취제', emoji: '💨', category: '위생용품', unit: '통' },
  { name: '방향제', emoji: '🌸', category: '위생용품', unit: '개' },
  { name: '제습제', emoji: '💧', category: '위생용품', unit: '개' },
  // 의약품
  { name: '타이레놀', emoji: '💊', category: '의약품', unit: '통' },
  { name: '감기약', emoji: '🤧', category: '의약품', unit: '통' },
  { name: '소화제', emoji: '💊', category: '의약품', unit: '통' },
  { name: '지사제', emoji: '💊', category: '의약품', unit: '통' },
  { name: '파스', emoji: '🩹', category: '의약품', unit: '매' },
  { name: '밴드', emoji: '🩹', category: '의약품', unit: '개' },
  { name: '연고', emoji: '🧴', category: '의약품', unit: '개' },
  { name: '소독약', emoji: '🧴', category: '의약품', unit: '병' },
  { name: '안약', emoji: '👁️', category: '의약품', unit: '개' },
  { name: '유산균', emoji: '💊', category: '의약품', unit: '통' },
  { name: '비타민', emoji: '💊', category: '의약품', unit: '통' },
  { name: '오메가3', emoji: '💊', category: '의약품', unit: '통' },
  { name: '영양제', emoji: '💪', category: '의약품', unit: '통' },
  // 화장품
  { name: '스킨', emoji: '💧', category: '화장품', unit: '병' },
  { name: '로션', emoji: '🧴', category: '화장품', unit: '병' },
  { name: '에센스', emoji: '✨', category: '화장품', unit: '병' },
  { name: '크림', emoji: '🫙', category: '화장품', unit: '통' },
  { name: '선크림', emoji: '☀️', category: '화장품', unit: '개' },
  { name: '클렌징폼', emoji: '🫧', category: '화장품', unit: '개' },
  { name: '마스크팩', emoji: '🧖', category: '화장품', unit: '장' },
  { name: '립밤', emoji: '💋', category: '화장품', unit: '개' },
  { name: '핸드크림', emoji: '🤲', category: '화장품', unit: '개' },
  { name: '바디로션', emoji: '🧴', category: '화장품', unit: '병' },
  // 주방용품
  { name: '랩', emoji: '🎞️', category: '주방용품', unit: '롤' },
  { name: '호일', emoji: '✨', category: '주방용품', unit: '롤' },
  { name: '종이호일', emoji: '📜', category: '주방용품', unit: '롤' },
  { name: '위생장갑', emoji: '🧤', category: '주방용품', unit: '장' },
  { name: '위생백', emoji: '🛍️', category: '주방용품', unit: '장' },
  { name: '종이컵', emoji: '🥤', category: '주방용품', unit: '개' },
  { name: '빨대', emoji: '🥤', category: '주방용품', unit: '개' },
  { name: '나무젓가락', emoji: '🥢', category: '주방용품', unit: '개' },
  { name: '일회용수저', emoji: '🥄', category: '주방용품', unit: '개' },
]

/** 입력 중 실시간 추천 — 부분 일치(완전 일치는 이미 선택된 셈이라 제외), 최대 limit개 */
export function suggestPresets(term: string, limit = 8): ItemPreset[] {
  const t = term.trim()
  if (!t) return []
  return ITEM_PRESETS.filter((p) => p.name.includes(t)).slice(0, limit)
}

/** 분류별 그룹 (카탈로그 = 시드 sort_order 순서 유지) */
export function groupPresets(list: ItemPreset[]): { category: string; items: ItemPreset[] }[] {
  const groups: { category: string; items: ItemPreset[] }[] = []
  for (const p of list) {
    const g = groups.find((x) => x.category === p.category)
    if (g) g.items.push(p)
    else groups.push({ category: p.category, items: [p] })
  }
  return groups
}
